-- MO HINH DU LIEU QUAN HE TU ERD QUAN LY NHAP XUAT

CREATE DATABASE IF NOT EXISTS QuanLyNhapXuat;
USE QuanLyNhapXuat;

CREATE TABLE PHIEUXUAT (
    SoPX VARCHAR(20) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE VATTU (
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(100) NOT NULL
);

CREATE TABLE PHIEUNHAP (
    SoPN VARCHAR(20) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE NHACC (
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255)
);

CREATE TABLE NHACC_SDT (
    MaNCC VARCHAR(20),
    SDT VARCHAR(20),
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE DONDH (
    SoDH VARCHAR(20) PRIMARY KEY,
    NgayDH DATE,
    MaNCC VARCHAR(20),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE CT_PHIEUXUAT (
    SoPX VARCHAR(20),
    MaVTU VARCHAR(20),
    DGXuat DECIMAL(15,2),
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CT_PHIEUNHAP (
    SoPN VARCHAR(20),
    MaVTU VARCHAR(20),
    DGNhap DECIMAL(15,2),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CT_DONDH (
    SoDH VARCHAR(20),
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

SHOW TABLES;
